spring:
  profiles:
    active: local
  application:
    name: springBase
  datasource:
    #    url: jdbc:h2:mem:testdb
    #    driver-class-name: org.h2.Driver
    # url: jdbc:log4jdbc:mysql://localhost:3306/mydb # 예시: MySQL 데이터베이스 사용 시
    # url: jdbc:log4jdbc:oracle:thin:@localhost:1521:xe # 예시: Oracle 데이터베이스 사용 시
    url: jdbc:log4jdbc:h2:mem:testdb
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: sa
    password:
  h2:
    console:
      enabled: true # H2 웹 콘솔 사용 허용
      path: /h2-console # 콘솔 접속 경로 (기본값)
  thymeleaf:
    cache: false # 템플릿 캐시 끄기 (개발용)
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.akmz.springBase.base.model
  configuration:
    mapUnderscoreToCamelCase: true
jwt:
  secret: ${JWT_SECRET_KEY}
  expiration: 3600000 # 1시간
  #  expiration: 1 # 만료 테스트용
  refresh-expiration: 604800000 # refreshToken: 7일 (ms 단위)

logging:
  config: classpath:config/log/log4j2.yml
